GET http://localhost:8000/subscribers

###

GET http://localhost:8000/subscribers/619a373ea805a2e284562aca


###
POST http://localhost:8000/subscribers
Content-Type: application/json

{
    "name" : "MY Name",
    "subscribedToChannel" : "Channel Name"
}

###

DELETE http://localhost:8000/subscribers/619a373ea805a2e284562aca

###

PATCH http://localhost:8000/subscribers/619a373ea805a2e284562aca
Content-Type: application/json

{
    "name": "New Name",
    "subscribedToChannel" : "New Channel"
}